// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtsl6a9IP5dvbhdLqlFgoLICNWt8hwtAk',
    appId: '1:259817493264:web:c29b9eb20003d108778b95',
    messagingSenderId: '259817493264',
    projectId: 'to-do-app-a0f5a',
    authDomain: 'to-do-app-a0f5a.firebaseapp.com',
    storageBucket: 'to-do-app-a0f5a.firebasestorage.app',
    measurementId: 'G-27F6CSZH1K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArt_qqQo2iEJt5xDfCKkAQwfKf2_PLpjk',
    appId: '1:259817493264:android:6d9965641ef3f465778b95',
    messagingSenderId: '259817493264',
    projectId: 'to-do-app-a0f5a',
    storageBucket: 'to-do-app-a0f5a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu2mFt0UQLocS5Ffwqic1n15MghulItuk',
    appId: '1:259817493264:ios:4ba8e2b84f1cffbf778b95',
    messagingSenderId: '259817493264',
    projectId: 'to-do-app-a0f5a',
    storageBucket: 'to-do-app-a0f5a.firebasestorage.app',
    iosBundleId: 'com.example.toDo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAu2mFt0UQLocS5Ffwqic1n15MghulItuk',
    appId: '1:259817493264:ios:4ba8e2b84f1cffbf778b95',
    messagingSenderId: '259817493264',
    projectId: 'to-do-app-a0f5a',
    storageBucket: 'to-do-app-a0f5a.firebasestorage.app',
    iosBundleId: 'com.example.toDo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtsl6a9IP5dvbhdLqlFgoLICNWt8hwtAk',
    appId: '1:259817493264:web:0af7120348c7037a778b95',
    messagingSenderId: '259817493264',
    projectId: 'to-do-app-a0f5a',
    authDomain: 'to-do-app-a0f5a.firebaseapp.com',
    storageBucket: 'to-do-app-a0f5a.firebasestorage.app',
    measurementId: 'G-EPHC8N6FDY',
  );
}
